#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET，是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 框架官网：http://www.rdiframework.net/
// 框架博客：http://blog.rdiframework.net/
// 版权所有：海南国思软件科技有限公司
// 交流QQ：406590790 
// 邮件交流：406590790@qq.com
// 其他博客：
//      http://www.cnblogs.com/huyong 
//      http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.Collections.Generic;
using System.Linq;

namespace RDIFramework.Test
{
    /// <summary>
    /// InterrogationTable
    /// 
    /// 
    /// 修改纪录
    /// 
    /// 2020-04-09 版本：3.6 yoky 创建主键。
    /// 
    /// 版本：3.6
    /// 
    /// <author>
    /// <name>yoky</name>
    /// <date>2020-04-09</date>
    /// </author>
    /// </summary>
    public partial class InterrogationTable
    {
        ///<summary>
        /// 表名
        ///</summary>
        [NonSerialized]
        public static string TableName = "interrogation";

        ///<summary>
        /// id
        ///</summary>
        [NonSerialized]
        public static string FieldId = "id";

        ///<summary>
        /// date
        ///</summary>
        [NonSerialized]
        public static string FieldDate = "date";

        ///<summary>
        /// patient_name
        ///</summary>
        [NonSerialized]
        public static string FieldPatientName = "patient_name";

        ///<summary>
        /// gender
        ///</summary>
        [NonSerialized]
        public static string FieldGender = "gender";

        ///<summary>
        /// birthday
        ///</summary>
        [NonSerialized]
        public static string FieldBirthday = "birthday";

        ///<summary>
        /// age
        ///</summary>
        [NonSerialized]
        public static string FieldAge = "age";

        ///<summary>
        /// occupation
        ///</summary>
        [NonSerialized]
        public static string FieldOccupation = "occupation";

        ///<summary>
        /// is_merry
        ///</summary>
        [NonSerialized]
        public static string FieldIsMerry = "is_merry";

        ///<summary>
        /// skin_color
        ///</summary>
        [NonSerialized]
        public static string FieldSkinColor = "skin_color";

        ///<summary>
        /// ethnic
        ///</summary>
        [NonSerialized]
        public static string FieldEthnic = "ethnic";

        ///<summary>
        /// hight
        ///</summary>
        [NonSerialized]
        public static string FieldHight = "hight";

        ///<summary>
        /// weight
        ///</summary>
        [NonSerialized]
        public static string FieldWeight = "weight";

        ///<summary>
        /// body_shape
        ///</summary>
        [NonSerialized]
        public static string FieldBodyShape = "body_shape";

        ///<summary>
        /// temperture
        ///</summary>
        [NonSerialized]
        public static string FieldTemperture = "temperture";

        ///<summary>
        /// heartrate
        ///</summary>
        [NonSerialized]
        public static string FieldHeartrate = "heartrate";

        ///<summary>
        /// blood_pressure_h
        ///</summary>
        [NonSerialized]
        public static string FieldBloodPressureH = "blood_pressure_h";

        ///<summary>
        /// blood_pressure_l
        ///</summary>
        [NonSerialized]
        public static string FieldBloodPressureL = "blood_pressure_l";

        ///<summary>
        /// address
        ///</summary>
        [NonSerialized]
        public static string FieldAddress = "address";

        ///<summary>
        /// zip_code
        ///</summary>
        [NonSerialized]
        public static string FieldZipCode = "zip_code";

        ///<summary>
        /// phone_number
        ///</summary>
        [NonSerialized]
        public static string FieldPhoneNumber = "phone_number";

        ///<summary>
        /// email
        ///</summary>
        [NonSerialized]
        public static string FieldEmail = "email";

        ///<summary>
        /// main_suit
        ///</summary>
        [NonSerialized]
        public static string FieldMainSuit = "main_suit";

        ///<summary>
        /// current_disease_condition
        ///</summary>
        [NonSerialized]
        public static string FieldCurrentDiseaseCondition = "current_disease_condition";

        ///<summary>
        /// disease_pattern
        ///</summary>
        [NonSerialized]
        public static string FieldDiseasePattern = "disease_pattern";

        ///<summary>
        /// medical_history
        ///</summary>
        [NonSerialized]
        public static string FieldMedicalHistory = "medical_history";

        ///<summary>
        /// blood_analysis
        ///</summary>
        [NonSerialized]
        public static string FieldBloodAnalysis = "blood_analysis";

        ///<summary>
        /// defecation
        ///</summary>
        [NonSerialized]
        public static string FieldDefecation = "defecation";

        ///<summary>
        /// liver_kidny
        ///</summary>
        [NonSerialized]
        public static string FieldLiverKidny = "liver_kidny";

        ///<summary>
        /// x_ray
        ///</summary>
        [NonSerialized]
        public static string FieldXRay = "x_ray";

        ///<summary>
        /// b_ultrasonic
        ///</summary>
        [NonSerialized]
        public static string FieldBUltrasonic = "b_ultrasonic";

        ///<summary>
        /// endoscopy
        ///</summary>
        [NonSerialized]
        public static string FieldEndoscopy = "endoscopy";

        ///<summary>
        /// ct
        ///</summary>
        [NonSerialized]
        public static string FieldCt = "ct";

        ///<summary>
        /// magnetic_resonance
        ///</summary>
        [NonSerialized]
        public static string FieldMagneticResonance = "magnetic_resonance";

        ///<summary>
        /// western_diagnosis
        ///</summary>
        [NonSerialized]
        public static string FieldWesternDiagnosis = "western_diagnosis";

        ///<summary>
        /// personnal_habit
        ///</summary>
        [NonSerialized]
        public static string FieldPersonnalHabit = "personnal_habit";

        ///<summary>
        /// personnal_sentiment
        ///</summary>
        [NonSerialized]
        public static string FieldPersonnalSentiment = "personnal_sentiment";

        ///<summary>
        /// family_history
        ///</summary>
        [NonSerialized]
        public static string FieldFamilyHistory = "family_history";

        ///<summary>
        /// is_longterm_hormones
        ///</summary>
        [NonSerialized]
        public static string FieldIsLongtermHormones = "is_longterm_hormones";

        ///<summary>
        /// is_amount_anticatarrhals
        ///</summary>
        [NonSerialized]
        public static string FieldIsAmountAnticatarrhals = "is_amount_anticatarrhals";

        ///<summary>
        /// drug_allergy
        ///</summary>
        [NonSerialized]
        public static string FieldDrugAllergy = "drug_allergy";

        ///<summary>
        /// curretn_drug
        ///</summary>
        [NonSerialized]
        public static string FieldCurretnDrug = "curretn_drug";

        ///<summary>
        /// operation_history
        ///</summary>
        [NonSerialized]
        public static string FieldOperationHistory = "operation_history";
    }
}
