//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDIFramework.Test.WCFBusinessDBProviderService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFBusinessDBProviderService.IDBProviderService")]
    public interface IDBProviderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBProviderService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IDBProviderService/ExecuteNonQueryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbParameter[]))]
        RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQueryResponse ExecuteNonQuery(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBProviderService/ExecuteNonQuery2", ReplyAction="http://tempuri.org/IDBProviderService/ExecuteNonQuery2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbParameter[]))]
        RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQuery2Response ExecuteNonQuery2(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQuery2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBProviderService/ExecuteScalar", ReplyAction="http://tempuri.org/IDBProviderService/ExecuteScalarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbParameter[]))]
        RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalarResponse ExecuteScalar(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBProviderService/ExecuteScalar2", ReplyAction="http://tempuri.org/IDBProviderService/ExecuteScalar2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbParameter[]))]
        RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalar2Response ExecuteScalar2(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalar2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBProviderService/Fill", ReplyAction="http://tempuri.org/IDBProviderService/FillResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbParameter[]))]
        RDIFramework.Test.WCFBusinessDBProviderService.FillResponse Fill(RDIFramework.Test.WCFBusinessDBProviderService.FillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBProviderService/Fill2", ReplyAction="http://tempuri.org/IDBProviderService/Fill2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DbParameter[]))]
        RDIFramework.Test.WCFBusinessDBProviderService.Fill2Response Fill2(RDIFramework.Test.WCFBusinessDBProviderService.Fill2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RDIFramework.Utilities")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codek__BackingFieldField;
        
        private string companyCodek__BackingFieldField;
        
        private string companyIdk__BackingFieldField;
        
        private string companyNamek__BackingFieldField;
        
        private string currentLanguagek__BackingFieldField;
        
        private string departmentCodek__BackingFieldField;
        
        private string departmentIdk__BackingFieldField;
        
        private string departmentNamek__BackingFieldField;
        
        private string iPAddressk__BackingFieldField;
        
        private string idk__BackingFieldField;
        
        private bool isAdministratork__BackingFieldField;
        
        private string lastVisitk__BackingFieldField;
        
        private string mACAddressk__BackingFieldField;
        
        private string openIdk__BackingFieldField;
        
        private string passwordk__BackingFieldField;
        
        private string processIdk__BackingFieldField;
        
        private string processNamek__BackingFieldField;
        
        private string realNamek__BackingFieldField;
        
        private string roleIdk__BackingFieldField;
        
        private string roleNamek__BackingFieldField;
        
        private int securityLevelk__BackingFieldField;
        
        private string servicePasswordk__BackingFieldField;
        
        private string serviceUserNamek__BackingFieldField;
        
        private string staffIdk__BackingFieldField;
        
        private string subCompanyCodek__BackingFieldField;
        
        private string subCompanyIdk__BackingFieldField;
        
        private string subCompanyNamek__BackingFieldField;
        
        private string targetUserIdk__BackingFieldField;
        
        private string themesk__BackingFieldField;
        
        private string userNamek__BackingFieldField;
        
        private string workgroupCodek__BackingFieldField;
        
        private string workgroupIdk__BackingFieldField;
        
        private string workgroupNamek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Code>k__BackingField", IsNullable=true, Order=0)]
        public string Codek__BackingField {
            get {
                return this.codek__BackingFieldField;
            }
            set {
                this.codek__BackingFieldField = value;
                this.RaisePropertyChanged("Codek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CompanyCode>k__BackingField", IsNullable=true, Order=1)]
        public string CompanyCodek__BackingField {
            get {
                return this.companyCodek__BackingFieldField;
            }
            set {
                this.companyCodek__BackingFieldField = value;
                this.RaisePropertyChanged("CompanyCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CompanyId>k__BackingField", IsNullable=true, Order=2)]
        public string CompanyIdk__BackingField {
            get {
                return this.companyIdk__BackingFieldField;
            }
            set {
                this.companyIdk__BackingFieldField = value;
                this.RaisePropertyChanged("CompanyIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CompanyName>k__BackingField", IsNullable=true, Order=3)]
        public string CompanyNamek__BackingField {
            get {
                return this.companyNamek__BackingFieldField;
            }
            set {
                this.companyNamek__BackingFieldField = value;
                this.RaisePropertyChanged("CompanyNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CurrentLanguage>k__BackingField", IsNullable=true, Order=4)]
        public string CurrentLanguagek__BackingField {
            get {
                return this.currentLanguagek__BackingFieldField;
            }
            set {
                this.currentLanguagek__BackingFieldField = value;
                this.RaisePropertyChanged("CurrentLanguagek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DepartmentCode>k__BackingField", IsNullable=true, Order=5)]
        public string DepartmentCodek__BackingField {
            get {
                return this.departmentCodek__BackingFieldField;
            }
            set {
                this.departmentCodek__BackingFieldField = value;
                this.RaisePropertyChanged("DepartmentCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DepartmentId>k__BackingField", IsNullable=true, Order=6)]
        public string DepartmentIdk__BackingField {
            get {
                return this.departmentIdk__BackingFieldField;
            }
            set {
                this.departmentIdk__BackingFieldField = value;
                this.RaisePropertyChanged("DepartmentIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DepartmentName>k__BackingField", IsNullable=true, Order=7)]
        public string DepartmentNamek__BackingField {
            get {
                return this.departmentNamek__BackingFieldField;
            }
            set {
                this.departmentNamek__BackingFieldField = value;
                this.RaisePropertyChanged("DepartmentNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<IPAddress>k__BackingField", IsNullable=true, Order=8)]
        public string IPAddressk__BackingField {
            get {
                return this.iPAddressk__BackingFieldField;
            }
            set {
                this.iPAddressk__BackingFieldField = value;
                this.RaisePropertyChanged("IPAddressk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Id>k__BackingField", IsNullable=true, Order=9)]
        public string Idk__BackingField {
            get {
                return this.idk__BackingFieldField;
            }
            set {
                this.idk__BackingFieldField = value;
                this.RaisePropertyChanged("Idk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<IsAdministrator>k__BackingField", Order=10)]
        public bool IsAdministratork__BackingField {
            get {
                return this.isAdministratork__BackingFieldField;
            }
            set {
                this.isAdministratork__BackingFieldField = value;
                this.RaisePropertyChanged("IsAdministratork__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastVisit>k__BackingField", IsNullable=true, Order=11)]
        public string LastVisitk__BackingField {
            get {
                return this.lastVisitk__BackingFieldField;
            }
            set {
                this.lastVisitk__BackingFieldField = value;
                this.RaisePropertyChanged("LastVisitk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<MACAddress>k__BackingField", IsNullable=true, Order=12)]
        public string MACAddressk__BackingField {
            get {
                return this.mACAddressk__BackingFieldField;
            }
            set {
                this.mACAddressk__BackingFieldField = value;
                this.RaisePropertyChanged("MACAddressk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<OpenId>k__BackingField", IsNullable=true, Order=13)]
        public string OpenIdk__BackingField {
            get {
                return this.openIdk__BackingFieldField;
            }
            set {
                this.openIdk__BackingFieldField = value;
                this.RaisePropertyChanged("OpenIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Password>k__BackingField", IsNullable=true, Order=14)]
        public string Passwordk__BackingField {
            get {
                return this.passwordk__BackingFieldField;
            }
            set {
                this.passwordk__BackingFieldField = value;
                this.RaisePropertyChanged("Passwordk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ProcessId>k__BackingField", IsNullable=true, Order=15)]
        public string ProcessIdk__BackingField {
            get {
                return this.processIdk__BackingFieldField;
            }
            set {
                this.processIdk__BackingFieldField = value;
                this.RaisePropertyChanged("ProcessIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ProcessName>k__BackingField", IsNullable=true, Order=16)]
        public string ProcessNamek__BackingField {
            get {
                return this.processNamek__BackingFieldField;
            }
            set {
                this.processNamek__BackingFieldField = value;
                this.RaisePropertyChanged("ProcessNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<RealName>k__BackingField", IsNullable=true, Order=17)]
        public string RealNamek__BackingField {
            get {
                return this.realNamek__BackingFieldField;
            }
            set {
                this.realNamek__BackingFieldField = value;
                this.RaisePropertyChanged("RealNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<RoleId>k__BackingField", IsNullable=true, Order=18)]
        public string RoleIdk__BackingField {
            get {
                return this.roleIdk__BackingFieldField;
            }
            set {
                this.roleIdk__BackingFieldField = value;
                this.RaisePropertyChanged("RoleIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<RoleName>k__BackingField", IsNullable=true, Order=19)]
        public string RoleNamek__BackingField {
            get {
                return this.roleNamek__BackingFieldField;
            }
            set {
                this.roleNamek__BackingFieldField = value;
                this.RaisePropertyChanged("RoleNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SecurityLevel>k__BackingField", Order=20)]
        public int SecurityLevelk__BackingField {
            get {
                return this.securityLevelk__BackingFieldField;
            }
            set {
                this.securityLevelk__BackingFieldField = value;
                this.RaisePropertyChanged("SecurityLevelk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ServicePassword>k__BackingField", IsNullable=true, Order=21)]
        public string ServicePasswordk__BackingField {
            get {
                return this.servicePasswordk__BackingFieldField;
            }
            set {
                this.servicePasswordk__BackingFieldField = value;
                this.RaisePropertyChanged("ServicePasswordk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ServiceUserName>k__BackingField", IsNullable=true, Order=22)]
        public string ServiceUserNamek__BackingField {
            get {
                return this.serviceUserNamek__BackingFieldField;
            }
            set {
                this.serviceUserNamek__BackingFieldField = value;
                this.RaisePropertyChanged("ServiceUserNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StaffId>k__BackingField", IsNullable=true, Order=23)]
        public string StaffIdk__BackingField {
            get {
                return this.staffIdk__BackingFieldField;
            }
            set {
                this.staffIdk__BackingFieldField = value;
                this.RaisePropertyChanged("StaffIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubCompanyCode>k__BackingField", IsNullable=true, Order=24)]
        public string SubCompanyCodek__BackingField {
            get {
                return this.subCompanyCodek__BackingFieldField;
            }
            set {
                this.subCompanyCodek__BackingFieldField = value;
                this.RaisePropertyChanged("SubCompanyCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubCompanyId>k__BackingField", IsNullable=true, Order=25)]
        public string SubCompanyIdk__BackingField {
            get {
                return this.subCompanyIdk__BackingFieldField;
            }
            set {
                this.subCompanyIdk__BackingFieldField = value;
                this.RaisePropertyChanged("SubCompanyIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubCompanyName>k__BackingField", IsNullable=true, Order=26)]
        public string SubCompanyNamek__BackingField {
            get {
                return this.subCompanyNamek__BackingFieldField;
            }
            set {
                this.subCompanyNamek__BackingFieldField = value;
                this.RaisePropertyChanged("SubCompanyNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<TargetUserId>k__BackingField", IsNullable=true, Order=27)]
        public string TargetUserIdk__BackingField {
            get {
                return this.targetUserIdk__BackingFieldField;
            }
            set {
                this.targetUserIdk__BackingFieldField = value;
                this.RaisePropertyChanged("TargetUserIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Themes>k__BackingField", IsNullable=true, Order=28)]
        public string Themesk__BackingField {
            get {
                return this.themesk__BackingFieldField;
            }
            set {
                this.themesk__BackingFieldField = value;
                this.RaisePropertyChanged("Themesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserName>k__BackingField", IsNullable=true, Order=29)]
        public string UserNamek__BackingField {
            get {
                return this.userNamek__BackingFieldField;
            }
            set {
                this.userNamek__BackingFieldField = value;
                this.RaisePropertyChanged("UserNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkgroupCode>k__BackingField", IsNullable=true, Order=30)]
        public string WorkgroupCodek__BackingField {
            get {
                return this.workgroupCodek__BackingFieldField;
            }
            set {
                this.workgroupCodek__BackingFieldField = value;
                this.RaisePropertyChanged("WorkgroupCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkgroupId>k__BackingField", IsNullable=true, Order=31)]
        public string WorkgroupIdk__BackingField {
            get {
                return this.workgroupIdk__BackingFieldField;
            }
            set {
                this.workgroupIdk__BackingFieldField = value;
                this.RaisePropertyChanged("WorkgroupIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkgroupName>k__BackingField", IsNullable=true, Order=32)]
        public string WorkgroupNamek__BackingField {
            get {
                return this.workgroupNamek__BackingFieldField;
            }
            set {
                this.workgroupNamek__BackingFieldField = value;
                this.RaisePropertyChanged("WorkgroupNamek__BackingField");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DbParameter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object @__identityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object @__identity {
            get {
                return this.@__identityField;
            }
            set {
                this.@__identityField = value;
                this.RaisePropertyChanged("__identity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
    public partial class DbParameter : MarshalByRefObject {
        
        private DbType dbTypeField;
        
        private bool dbTypeFieldSpecified;
        
        private ParameterDirection directionField;
        
        private bool directionFieldSpecified;
        
        private bool isNullableField;
        
        private bool isNullableFieldSpecified;
        
        private string parameterNameField;
        
        private byte precisionField;
        
        private bool precisionFieldSpecified;
        
        private byte scaleField;
        
        private bool scaleFieldSpecified;
        
        private int sizeField;
        
        private bool sizeFieldSpecified;
        
        private string sourceColumnField;
        
        private bool sourceColumnNullMappingField;
        
        private bool sourceColumnNullMappingFieldSpecified;
        
        private DataRowVersion sourceVersionField;
        
        private bool sourceVersionFieldSpecified;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DbType DbType {
            get {
                return this.dbTypeField;
            }
            set {
                this.dbTypeField = value;
                this.RaisePropertyChanged("DbType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DbTypeSpecified {
            get {
                return this.dbTypeFieldSpecified;
            }
            set {
                this.dbTypeFieldSpecified = value;
                this.RaisePropertyChanged("DbTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ParameterDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectionSpecified {
            get {
                return this.directionFieldSpecified;
            }
            set {
                this.directionFieldSpecified = value;
                this.RaisePropertyChanged("DirectionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsNullable {
            get {
                return this.isNullableField;
            }
            set {
                this.isNullableField = value;
                this.RaisePropertyChanged("IsNullable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsNullableSpecified {
            get {
                return this.isNullableFieldSpecified;
            }
            set {
                this.isNullableFieldSpecified = value;
                this.RaisePropertyChanged("IsNullableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ParameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
                this.RaisePropertyChanged("ParameterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public byte Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
                this.RaisePropertyChanged("Precision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrecisionSpecified {
            get {
                return this.precisionFieldSpecified;
            }
            set {
                this.precisionFieldSpecified = value;
                this.RaisePropertyChanged("PrecisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
                this.RaisePropertyChanged("Scale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScaleSpecified {
            get {
                return this.scaleFieldSpecified;
            }
            set {
                this.scaleFieldSpecified = value;
                this.RaisePropertyChanged("ScaleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string SourceColumn {
            get {
                return this.sourceColumnField;
            }
            set {
                this.sourceColumnField = value;
                this.RaisePropertyChanged("SourceColumn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool SourceColumnNullMapping {
            get {
                return this.sourceColumnNullMappingField;
            }
            set {
                this.sourceColumnNullMappingField = value;
                this.RaisePropertyChanged("SourceColumnNullMapping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceColumnNullMappingSpecified {
            get {
                return this.sourceColumnNullMappingFieldSpecified;
            }
            set {
                this.sourceColumnNullMappingFieldSpecified = value;
                this.RaisePropertyChanged("SourceColumnNullMappingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public DataRowVersion SourceVersion {
            get {
                return this.sourceVersionField;
            }
            set {
                this.sourceVersionField = value;
                this.RaisePropertyChanged("SourceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceVersionSpecified {
            get {
                return this.sourceVersionFieldSpecified;
            }
            set {
                this.sourceVersionFieldSpecified = value;
                this.RaisePropertyChanged("SourceVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum DbType {
        
        /// <remarks/>
        AnsiString,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Currency,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        Object,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Time,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        VarNumeric,
        
        /// <remarks/>
        AnsiStringFixedLength,
        
        /// <remarks/>
        StringFixedLength,
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        DateTime2,
        
        /// <remarks/>
        DateTimeOffset,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum ParameterDirection {
        
        /// <remarks/>
        Input,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        InputOutput,
        
        /// <remarks/>
        ReturnValue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum DataRowVersion {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        Proposed,
        
        /// <remarks/>
        Default,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteNonQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteNonQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandText;
        
        public ExecuteNonQueryRequest() {
        }
        
        public ExecuteNonQueryRequest(RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo, string commandText) {
            this.userInfo = userInfo;
            this.commandText = commandText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteNonQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteNonQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ExecuteNonQueryResult;
        
        public ExecuteNonQueryResponse() {
        }
        
        public ExecuteNonQueryResponse(int ExecuteNonQueryResult) {
            this.ExecuteNonQueryResult = ExecuteNonQueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteNonQuery2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteNonQuery2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        public RDIFramework.Test.WCFBusinessDBProviderService.DbParameter[] dbParameters;
        
        public ExecuteNonQuery2Request() {
        }
        
        public ExecuteNonQuery2Request(RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo, string commandText, RDIFramework.Test.WCFBusinessDBProviderService.DbParameter[] dbParameters) {
            this.userInfo = userInfo;
            this.commandText = commandText;
            this.dbParameters = dbParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteNonQuery2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteNonQuery2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ExecuteNonQuery2Result;
        
        public ExecuteNonQuery2Response() {
        }
        
        public ExecuteNonQuery2Response(int ExecuteNonQuery2Result) {
            this.ExecuteNonQuery2Result = ExecuteNonQuery2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteScalar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteScalarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandText;
        
        public ExecuteScalarRequest() {
        }
        
        public ExecuteScalarRequest(RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo, string commandText) {
            this.userInfo = userInfo;
            this.commandText = commandText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteScalarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteScalarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ExecuteScalarResult;
        
        public ExecuteScalarResponse() {
        }
        
        public ExecuteScalarResponse(object ExecuteScalarResult) {
            this.ExecuteScalarResult = ExecuteScalarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteScalar2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteScalar2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        public RDIFramework.Test.WCFBusinessDBProviderService.DbParameter[] dbParameters;
        
        public ExecuteScalar2Request() {
        }
        
        public ExecuteScalar2Request(RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo, string commandText, RDIFramework.Test.WCFBusinessDBProviderService.DbParameter[] dbParameters) {
            this.userInfo = userInfo;
            this.commandText = commandText;
            this.dbParameters = dbParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteScalar2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteScalar2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object ExecuteScalar2Result;
        
        public ExecuteScalar2Response() {
        }
        
        public ExecuteScalar2Response(object ExecuteScalar2Result) {
            this.ExecuteScalar2Result = ExecuteScalar2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandText;
        
        public FillRequest() {
        }
        
        public FillRequest(RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo, string commandText) {
            this.userInfo = userInfo;
            this.commandText = commandText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable FillResult;
        
        public FillResponse() {
        }
        
        public FillResponse(System.Data.DataTable FillResult) {
            this.FillResult = FillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fill2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Fill2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data.Common")]
        public RDIFramework.Test.WCFBusinessDBProviderService.DbParameter[] dbParameters;
        
        public Fill2Request() {
        }
        
        public Fill2Request(RDIFramework.Test.WCFBusinessDBProviderService.UserInfo userInfo, string commandText, RDIFramework.Test.WCFBusinessDBProviderService.DbParameter[] dbParameters) {
            this.userInfo = userInfo;
            this.commandText = commandText;
            this.dbParameters = dbParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fill2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Fill2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable Fill2Result;
        
        public Fill2Response() {
        }
        
        public Fill2Response(System.Data.DataTable Fill2Result) {
            this.Fill2Result = Fill2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBProviderServiceChannel : RDIFramework.Test.WCFBusinessDBProviderService.IDBProviderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBProviderServiceClient : System.ServiceModel.ClientBase<RDIFramework.Test.WCFBusinessDBProviderService.IDBProviderService>, RDIFramework.Test.WCFBusinessDBProviderService.IDBProviderService {
        
        public DBProviderServiceClient() {
        }
        
        public DBProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQueryResponse ExecuteNonQuery(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQueryRequest request) {
            return base.Channel.ExecuteNonQuery(request);
        }
        
        public RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQuery2Response ExecuteNonQuery2(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteNonQuery2Request request) {
            return base.Channel.ExecuteNonQuery2(request);
        }
        
        public RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalarResponse ExecuteScalar(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalarRequest request) {
            return base.Channel.ExecuteScalar(request);
        }
        
        public RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalar2Response ExecuteScalar2(RDIFramework.Test.WCFBusinessDBProviderService.ExecuteScalar2Request request) {
            return base.Channel.ExecuteScalar2(request);
        }
        
        public RDIFramework.Test.WCFBusinessDBProviderService.FillResponse Fill(RDIFramework.Test.WCFBusinessDBProviderService.FillRequest request) {
            return base.Channel.Fill(request);
        }
        
        public RDIFramework.Test.WCFBusinessDBProviderService.Fill2Response Fill2(RDIFramework.Test.WCFBusinessDBProviderService.Fill2Request request) {
            return base.Channel.Fill2(request);
        }
    }
}
