//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDIFramework.Test.WCFDemoProductService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFDemoProductService.IDemoProductService")]
    public interface IDemoProductService {
        
        // CODEGEN: 参数“AddResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/Add", ReplyAction="http://tempuri.org/IDemoProductService/AddResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.AddResponse Add(RDIFramework.Test.WCFDemoProductService.AddRequest request);
        
        // CODEGEN: 参数“userInfo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/Update", ReplyAction="http://tempuri.org/IDemoProductService/UpdateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.UpdateResponse Update(RDIFramework.Test.WCFDemoProductService.UpdateRequest request);
        
        // CODEGEN: 参数“GetDTResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/GetDT", ReplyAction="http://tempuri.org/IDemoProductService/GetDTResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.GetDTResponse GetDT(RDIFramework.Test.WCFDemoProductService.GetDTRequest request);
        
        // CODEGEN: 参数“GetDTByPageResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/GetDTByPage", ReplyAction="http://tempuri.org/IDemoProductService/GetDTByPageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.GetDTByPageResponse GetDTByPage(RDIFramework.Test.WCFDemoProductService.GetDTByPageRequest request);
        
        // CODEGEN: 参数“GetEntityResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/GetEntity", ReplyAction="http://tempuri.org/IDemoProductService/GetEntityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.GetEntityResponse GetEntity(RDIFramework.Test.WCFDemoProductService.GetEntityRequest request);
        
        // CODEGEN: 参数“GetDTByIdsResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/GetDTByIds", ReplyAction="http://tempuri.org/IDemoProductService/GetDTByIdsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.GetDTByIdsResponse GetDTByIds(RDIFramework.Test.WCFDemoProductService.GetDTByIdsRequest request);
        
        // CODEGEN: 参数“GetDTByValuesResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/GetDTByValues", ReplyAction="http://tempuri.org/IDemoProductService/GetDTByValuesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.GetDTByValuesResponse GetDTByValues(RDIFramework.Test.WCFDemoProductService.GetDTByValuesRequest request);
        
        // CODEGEN: 参数“userInfo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/BatchSave", ReplyAction="http://tempuri.org/IDemoProductService/BatchSaveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.BatchSaveResponse BatchSave(RDIFramework.Test.WCFDemoProductService.BatchSaveRequest request);
        
        // CODEGEN: 参数“userInfo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/Delete", ReplyAction="http://tempuri.org/IDemoProductService/DeleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.DeleteResponse Delete(RDIFramework.Test.WCFDemoProductService.DeleteRequest request);
        
        // CODEGEN: 参数“userInfo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/BatchDelete", ReplyAction="http://tempuri.org/IDemoProductService/BatchDeleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.BatchDeleteResponse BatchDelete(RDIFramework.Test.WCFDemoProductService.BatchDeleteRequest request);
        
        // CODEGEN: 参数“userInfo”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoProductService/SetDeleted", ReplyAction="http://tempuri.org/IDemoProductService/SetDeletedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfstringanyType[]))]
        RDIFramework.Test.WCFDemoProductService.SetDeletedResponse SetDeleted(RDIFramework.Test.WCFDemoProductService.SetDeletedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RDIFramework.Utilities")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codek__BackingFieldField;
        
        private string companyCodek__BackingFieldField;
        
        private string companyIdk__BackingFieldField;
        
        private string companyNamek__BackingFieldField;
        
        private string currentLanguagek__BackingFieldField;
        
        private string departmentCodek__BackingFieldField;
        
        private string departmentIdk__BackingFieldField;
        
        private string departmentNamek__BackingFieldField;
        
        private string iPAddressk__BackingFieldField;
        
        private string idk__BackingFieldField;
        
        private bool isAdministratork__BackingFieldField;
        
        private string lastVisitk__BackingFieldField;
        
        private string mACAddressk__BackingFieldField;
        
        private string openIdk__BackingFieldField;
        
        private string passwordk__BackingFieldField;
        
        private string processIdk__BackingFieldField;
        
        private string processNamek__BackingFieldField;
        
        private string realNamek__BackingFieldField;
        
        private string roleIdk__BackingFieldField;
        
        private string roleNamek__BackingFieldField;
        
        private int securityLevelk__BackingFieldField;
        
        private string servicePasswordk__BackingFieldField;
        
        private string serviceUserNamek__BackingFieldField;
        
        private string staffIdk__BackingFieldField;
        
        private string subCompanyCodek__BackingFieldField;
        
        private string subCompanyIdk__BackingFieldField;
        
        private string subCompanyNamek__BackingFieldField;
        
        private string targetUserIdk__BackingFieldField;
        
        private string themesk__BackingFieldField;
        
        private string userNamek__BackingFieldField;
        
        private string workgroupCodek__BackingFieldField;
        
        private string workgroupIdk__BackingFieldField;
        
        private string workgroupNamek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Code>k__BackingField", IsNullable=true, Order=0)]
        public string Codek__BackingField {
            get {
                return this.codek__BackingFieldField;
            }
            set {
                this.codek__BackingFieldField = value;
                this.RaisePropertyChanged("Codek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CompanyCode>k__BackingField", IsNullable=true, Order=1)]
        public string CompanyCodek__BackingField {
            get {
                return this.companyCodek__BackingFieldField;
            }
            set {
                this.companyCodek__BackingFieldField = value;
                this.RaisePropertyChanged("CompanyCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CompanyId>k__BackingField", IsNullable=true, Order=2)]
        public string CompanyIdk__BackingField {
            get {
                return this.companyIdk__BackingFieldField;
            }
            set {
                this.companyIdk__BackingFieldField = value;
                this.RaisePropertyChanged("CompanyIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CompanyName>k__BackingField", IsNullable=true, Order=3)]
        public string CompanyNamek__BackingField {
            get {
                return this.companyNamek__BackingFieldField;
            }
            set {
                this.companyNamek__BackingFieldField = value;
                this.RaisePropertyChanged("CompanyNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CurrentLanguage>k__BackingField", IsNullable=true, Order=4)]
        public string CurrentLanguagek__BackingField {
            get {
                return this.currentLanguagek__BackingFieldField;
            }
            set {
                this.currentLanguagek__BackingFieldField = value;
                this.RaisePropertyChanged("CurrentLanguagek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DepartmentCode>k__BackingField", IsNullable=true, Order=5)]
        public string DepartmentCodek__BackingField {
            get {
                return this.departmentCodek__BackingFieldField;
            }
            set {
                this.departmentCodek__BackingFieldField = value;
                this.RaisePropertyChanged("DepartmentCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DepartmentId>k__BackingField", IsNullable=true, Order=6)]
        public string DepartmentIdk__BackingField {
            get {
                return this.departmentIdk__BackingFieldField;
            }
            set {
                this.departmentIdk__BackingFieldField = value;
                this.RaisePropertyChanged("DepartmentIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DepartmentName>k__BackingField", IsNullable=true, Order=7)]
        public string DepartmentNamek__BackingField {
            get {
                return this.departmentNamek__BackingFieldField;
            }
            set {
                this.departmentNamek__BackingFieldField = value;
                this.RaisePropertyChanged("DepartmentNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<IPAddress>k__BackingField", IsNullable=true, Order=8)]
        public string IPAddressk__BackingField {
            get {
                return this.iPAddressk__BackingFieldField;
            }
            set {
                this.iPAddressk__BackingFieldField = value;
                this.RaisePropertyChanged("IPAddressk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Id>k__BackingField", IsNullable=true, Order=9)]
        public string Idk__BackingField {
            get {
                return this.idk__BackingFieldField;
            }
            set {
                this.idk__BackingFieldField = value;
                this.RaisePropertyChanged("Idk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<IsAdministrator>k__BackingField", Order=10)]
        public bool IsAdministratork__BackingField {
            get {
                return this.isAdministratork__BackingFieldField;
            }
            set {
                this.isAdministratork__BackingFieldField = value;
                this.RaisePropertyChanged("IsAdministratork__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastVisit>k__BackingField", IsNullable=true, Order=11)]
        public string LastVisitk__BackingField {
            get {
                return this.lastVisitk__BackingFieldField;
            }
            set {
                this.lastVisitk__BackingFieldField = value;
                this.RaisePropertyChanged("LastVisitk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<MACAddress>k__BackingField", IsNullable=true, Order=12)]
        public string MACAddressk__BackingField {
            get {
                return this.mACAddressk__BackingFieldField;
            }
            set {
                this.mACAddressk__BackingFieldField = value;
                this.RaisePropertyChanged("MACAddressk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<OpenId>k__BackingField", IsNullable=true, Order=13)]
        public string OpenIdk__BackingField {
            get {
                return this.openIdk__BackingFieldField;
            }
            set {
                this.openIdk__BackingFieldField = value;
                this.RaisePropertyChanged("OpenIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Password>k__BackingField", IsNullable=true, Order=14)]
        public string Passwordk__BackingField {
            get {
                return this.passwordk__BackingFieldField;
            }
            set {
                this.passwordk__BackingFieldField = value;
                this.RaisePropertyChanged("Passwordk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ProcessId>k__BackingField", IsNullable=true, Order=15)]
        public string ProcessIdk__BackingField {
            get {
                return this.processIdk__BackingFieldField;
            }
            set {
                this.processIdk__BackingFieldField = value;
                this.RaisePropertyChanged("ProcessIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ProcessName>k__BackingField", IsNullable=true, Order=16)]
        public string ProcessNamek__BackingField {
            get {
                return this.processNamek__BackingFieldField;
            }
            set {
                this.processNamek__BackingFieldField = value;
                this.RaisePropertyChanged("ProcessNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<RealName>k__BackingField", IsNullable=true, Order=17)]
        public string RealNamek__BackingField {
            get {
                return this.realNamek__BackingFieldField;
            }
            set {
                this.realNamek__BackingFieldField = value;
                this.RaisePropertyChanged("RealNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<RoleId>k__BackingField", IsNullable=true, Order=18)]
        public string RoleIdk__BackingField {
            get {
                return this.roleIdk__BackingFieldField;
            }
            set {
                this.roleIdk__BackingFieldField = value;
                this.RaisePropertyChanged("RoleIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<RoleName>k__BackingField", IsNullable=true, Order=19)]
        public string RoleNamek__BackingField {
            get {
                return this.roleNamek__BackingFieldField;
            }
            set {
                this.roleNamek__BackingFieldField = value;
                this.RaisePropertyChanged("RoleNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SecurityLevel>k__BackingField", Order=20)]
        public int SecurityLevelk__BackingField {
            get {
                return this.securityLevelk__BackingFieldField;
            }
            set {
                this.securityLevelk__BackingFieldField = value;
                this.RaisePropertyChanged("SecurityLevelk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ServicePassword>k__BackingField", IsNullable=true, Order=21)]
        public string ServicePasswordk__BackingField {
            get {
                return this.servicePasswordk__BackingFieldField;
            }
            set {
                this.servicePasswordk__BackingFieldField = value;
                this.RaisePropertyChanged("ServicePasswordk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ServiceUserName>k__BackingField", IsNullable=true, Order=22)]
        public string ServiceUserNamek__BackingField {
            get {
                return this.serviceUserNamek__BackingFieldField;
            }
            set {
                this.serviceUserNamek__BackingFieldField = value;
                this.RaisePropertyChanged("ServiceUserNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StaffId>k__BackingField", IsNullable=true, Order=23)]
        public string StaffIdk__BackingField {
            get {
                return this.staffIdk__BackingFieldField;
            }
            set {
                this.staffIdk__BackingFieldField = value;
                this.RaisePropertyChanged("StaffIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubCompanyCode>k__BackingField", IsNullable=true, Order=24)]
        public string SubCompanyCodek__BackingField {
            get {
                return this.subCompanyCodek__BackingFieldField;
            }
            set {
                this.subCompanyCodek__BackingFieldField = value;
                this.RaisePropertyChanged("SubCompanyCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubCompanyId>k__BackingField", IsNullable=true, Order=25)]
        public string SubCompanyIdk__BackingField {
            get {
                return this.subCompanyIdk__BackingFieldField;
            }
            set {
                this.subCompanyIdk__BackingFieldField = value;
                this.RaisePropertyChanged("SubCompanyIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubCompanyName>k__BackingField", IsNullable=true, Order=26)]
        public string SubCompanyNamek__BackingField {
            get {
                return this.subCompanyNamek__BackingFieldField;
            }
            set {
                this.subCompanyNamek__BackingFieldField = value;
                this.RaisePropertyChanged("SubCompanyNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<TargetUserId>k__BackingField", IsNullable=true, Order=27)]
        public string TargetUserIdk__BackingField {
            get {
                return this.targetUserIdk__BackingFieldField;
            }
            set {
                this.targetUserIdk__BackingFieldField = value;
                this.RaisePropertyChanged("TargetUserIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Themes>k__BackingField", IsNullable=true, Order=28)]
        public string Themesk__BackingField {
            get {
                return this.themesk__BackingFieldField;
            }
            set {
                this.themesk__BackingFieldField = value;
                this.RaisePropertyChanged("Themesk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserName>k__BackingField", IsNullable=true, Order=29)]
        public string UserNamek__BackingField {
            get {
                return this.userNamek__BackingFieldField;
            }
            set {
                this.userNamek__BackingFieldField = value;
                this.RaisePropertyChanged("UserNamek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkgroupCode>k__BackingField", IsNullable=true, Order=30)]
        public string WorkgroupCodek__BackingField {
            get {
                return this.workgroupCodek__BackingFieldField;
            }
            set {
                this.workgroupCodek__BackingFieldField = value;
                this.RaisePropertyChanged("WorkgroupCodek__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkgroupId>k__BackingField", IsNullable=true, Order=31)]
        public string WorkgroupIdk__BackingField {
            get {
                return this.workgroupIdk__BackingFieldField;
            }
            set {
                this.workgroupIdk__BackingFieldField = value;
                this.RaisePropertyChanged("WorkgroupIdk__BackingField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkgroupName>k__BackingField", IsNullable=true, Order=32)]
        public string WorkgroupNamek__BackingField {
            get {
                return this.workgroupNamek__BackingFieldField;
            }
            set {
                this.workgroupNamek__BackingFieldField = value;
                this.RaisePropertyChanged("WorkgroupNamek__BackingField");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic")]
    public partial class KeyValuePairOfstringanyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DemoProductEntity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RDIFramework.BizLogic")]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RDIFrameworkDemo.BizLogic")]
    public partial class DemoProductEntity : BaseEntity {
        
        private string _createByField;
        
        private System.Nullable<System.DateTime> _createOnField;
        
        private string _createUserIdField;
        
        private System.Nullable<int> _deleteMarkField;
        
        private string _descriptionField;
        
        private System.Nullable<int> _enabledField;
        
        private string _iDField;
        
        private string _modifiedByField;
        
        private System.Nullable<System.DateTime> _modifiedOnField;
        
        private string _modifiedUserIdField;
        
        private string _productCodeField;
        
        private string _productNameField;
        
        private System.Nullable<decimal> _productPriceField;
        
        private string _productUnitField;
        
        private System.Nullable<int> _sortCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string _createBy {
            get {
                return this._createByField;
            }
            set {
                this._createByField = value;
                this.RaisePropertyChanged("_createBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> _createOn {
            get {
                return this._createOnField;
            }
            set {
                this._createOnField = value;
                this.RaisePropertyChanged("_createOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string _createUserId {
            get {
                return this._createUserIdField;
            }
            set {
                this._createUserIdField = value;
                this.RaisePropertyChanged("_createUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> _deleteMark {
            get {
                return this._deleteMarkField;
            }
            set {
                this._deleteMarkField = value;
                this.RaisePropertyChanged("_deleteMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string _description {
            get {
                return this._descriptionField;
            }
            set {
                this._descriptionField = value;
                this.RaisePropertyChanged("_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> _enabled {
            get {
                return this._enabledField;
            }
            set {
                this._enabledField = value;
                this.RaisePropertyChanged("_enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string _iD {
            get {
                return this._iDField;
            }
            set {
                this._iDField = value;
                this.RaisePropertyChanged("_iD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string _modifiedBy {
            get {
                return this._modifiedByField;
            }
            set {
                this._modifiedByField = value;
                this.RaisePropertyChanged("_modifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> _modifiedOn {
            get {
                return this._modifiedOnField;
            }
            set {
                this._modifiedOnField = value;
                this.RaisePropertyChanged("_modifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string _modifiedUserId {
            get {
                return this._modifiedUserIdField;
            }
            set {
                this._modifiedUserIdField = value;
                this.RaisePropertyChanged("_modifiedUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string _productCode {
            get {
                return this._productCodeField;
            }
            set {
                this._productCodeField = value;
                this.RaisePropertyChanged("_productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string _productName {
            get {
                return this._productNameField;
            }
            set {
                this._productNameField = value;
                this.RaisePropertyChanged("_productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> _productPrice {
            get {
                return this._productPriceField;
            }
            set {
                this._productPriceField = value;
                this.RaisePropertyChanged("_productPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string _productUnit {
            get {
                return this._productUnitField;
            }
            set {
                this._productUnitField = value;
                this.RaisePropertyChanged("_productUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> _sortCode {
            get {
                return this._sortCodeField;
            }
            set {
                this._sortCodeField = value;
                this.RaisePropertyChanged("_sortCode");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.DemoProductEntity entity;
        
        public AddRequest() {
        }
        
        public AddRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.DemoProductEntity entity) {
            this.userInfo = userInfo;
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusMessage;
        
        public AddResponse() {
        }
        
        public AddResponse(string AddResult, string statusCode, string statusMessage) {
            this.AddResult = AddResult;
            this.statusCode = statusCode;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.DemoProductEntity entity;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.DemoProductEntity entity) {
            this.userInfo = userInfo;
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusMessage;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(int UpdateResult, string statusCode, string statusMessage) {
            this.UpdateResult = UpdateResult;
            this.statusCode = statusCode;
            this.statusMessage = statusMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        public GetDTRequest() {
        }
        
        public GetDTRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo) {
            this.userInfo = userInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDTResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDTResult;
        
        public GetDTResponse() {
        }
        
        public GetDTResponse(System.Data.DataTable GetDTResult) {
            this.GetDTResult = GetDTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDTByPage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTByPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string searchValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sortExpression;
        
        public GetDTByPageRequest() {
        }
        
        public GetDTByPageRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string searchValue, int pageIndex, int pageSize, string sortExpression) {
            this.userInfo = userInfo;
            this.searchValue = searchValue;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.sortExpression = sortExpression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDTByPageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTByPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDTByPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int recordCount;
        
        public GetDTByPageResponse() {
        }
        
        public GetDTByPageResponse(System.Data.DataTable GetDTByPageResult, int recordCount) {
            this.GetDTByPageResult = GetDTByPageResult;
            this.recordCount = recordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEntityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetEntityRequest() {
        }
        
        public GetEntityRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string id) {
            this.userInfo = userInfo;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEntityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.DemoProductEntity GetEntityResult;
        
        public GetEntityResponse() {
        }
        
        public GetEntityResponse(RDIFramework.Test.WCFDemoProductService.DemoProductEntity GetEntityResult) {
            this.GetEntityResult = GetEntityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDTByIds", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTByIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ids;
        
        public GetDTByIdsRequest() {
        }
        
        public GetDTByIdsRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string[] ids) {
            this.userInfo = userInfo;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDTByIdsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTByIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDTByIdsResult;
        
        public GetDTByIdsResponse() {
        }
        
        public GetDTByIdsResponse(System.Data.DataTable GetDTByIdsResult) {
            this.GetDTByIdsResult = GetDTByIdsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDTByValues", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTByValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic", IsNullable=false)]
        public RDIFramework.Test.WCFDemoProductService.KeyValuePairOfstringanyType[] parameters;
        
        public GetDTByValuesRequest() {
        }
        
        public GetDTByValuesRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.KeyValuePairOfstringanyType[] parameters) {
            this.userInfo = userInfo;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDTByValuesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDTByValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDTByValuesResult;
        
        public GetDTByValuesResponse() {
        }
        
        public GetDTByValuesResponse(System.Data.DataTable GetDTByValuesResult) {
            this.GetDTByValuesResult = GetDTByValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSave", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BatchSaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RDIFrameworkDemo.BizLogic")]
        public RDIFramework.Test.WCFDemoProductService.DemoProductEntity[] entites;
        
        public BatchSaveRequest() {
        }
        
        public BatchSaveRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.DemoProductEntity[] entites) {
            this.userInfo = userInfo;
            this.entites = entites;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchSaveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BatchSaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int BatchSaveResult;
        
        public BatchSaveResponse() {
        }
        
        public BatchSaveResponse(int BatchSaveResult) {
            this.BatchSaveResult = BatchSaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string id) {
            this.userInfo = userInfo;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int DeleteResult;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(int DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchDelete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BatchDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ids;
        
        public BatchDeleteRequest() {
        }
        
        public BatchDeleteRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string[] ids) {
            this.userInfo = userInfo;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchDeleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BatchDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int BatchDeleteResult;
        
        public BatchDeleteResponse() {
        }
        
        public BatchDeleteResponse(int BatchDeleteResult) {
            this.BatchDeleteResult = BatchDeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDeleted", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetDeletedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RDIFramework.Test.WCFDemoProductService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ids;
        
        public SetDeletedRequest() {
        }
        
        public SetDeletedRequest(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string[] ids) {
            this.userInfo = userInfo;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDeletedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetDeletedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SetDeletedResult;
        
        public SetDeletedResponse() {
        }
        
        public SetDeletedResponse(int SetDeletedResult) {
            this.SetDeletedResult = SetDeletedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoProductServiceChannel : RDIFramework.Test.WCFDemoProductService.IDemoProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoProductServiceClient : System.ServiceModel.ClientBase<RDIFramework.Test.WCFDemoProductService.IDemoProductService>, RDIFramework.Test.WCFDemoProductService.IDemoProductService {
        
        public DemoProductServiceClient() {
        }
        
        public DemoProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.AddResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.Add(RDIFramework.Test.WCFDemoProductService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public string Add(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.DemoProductEntity entity, out string statusCode, out string statusMessage) {
            RDIFramework.Test.WCFDemoProductService.AddRequest inValue = new RDIFramework.Test.WCFDemoProductService.AddRequest();
            inValue.userInfo = userInfo;
            inValue.entity = entity;
            RDIFramework.Test.WCFDemoProductService.AddResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).Add(inValue);
            statusCode = retVal.statusCode;
            statusMessage = retVal.statusMessage;
            return retVal.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.UpdateResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.Update(RDIFramework.Test.WCFDemoProductService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.DemoProductEntity entity, out string statusCode, out string statusMessage) {
            RDIFramework.Test.WCFDemoProductService.UpdateRequest inValue = new RDIFramework.Test.WCFDemoProductService.UpdateRequest();
            inValue.userInfo = userInfo;
            inValue.entity = entity;
            RDIFramework.Test.WCFDemoProductService.UpdateResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).Update(inValue);
            statusCode = retVal.statusCode;
            statusMessage = retVal.statusMessage;
            return retVal.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.GetDTResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.GetDT(RDIFramework.Test.WCFDemoProductService.GetDTRequest request) {
            return base.Channel.GetDT(request);
        }
        
        public System.Data.DataTable GetDT(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo) {
            RDIFramework.Test.WCFDemoProductService.GetDTRequest inValue = new RDIFramework.Test.WCFDemoProductService.GetDTRequest();
            inValue.userInfo = userInfo;
            RDIFramework.Test.WCFDemoProductService.GetDTResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).GetDT(inValue);
            return retVal.GetDTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.GetDTByPageResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.GetDTByPage(RDIFramework.Test.WCFDemoProductService.GetDTByPageRequest request) {
            return base.Channel.GetDTByPage(request);
        }
        
        public System.Data.DataTable GetDTByPage(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string searchValue, int pageIndex, int pageSize, string sortExpression, out int recordCount) {
            RDIFramework.Test.WCFDemoProductService.GetDTByPageRequest inValue = new RDIFramework.Test.WCFDemoProductService.GetDTByPageRequest();
            inValue.userInfo = userInfo;
            inValue.searchValue = searchValue;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.sortExpression = sortExpression;
            RDIFramework.Test.WCFDemoProductService.GetDTByPageResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).GetDTByPage(inValue);
            recordCount = retVal.recordCount;
            return retVal.GetDTByPageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.GetEntityResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.GetEntity(RDIFramework.Test.WCFDemoProductService.GetEntityRequest request) {
            return base.Channel.GetEntity(request);
        }
        
        public RDIFramework.Test.WCFDemoProductService.DemoProductEntity GetEntity(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string id) {
            RDIFramework.Test.WCFDemoProductService.GetEntityRequest inValue = new RDIFramework.Test.WCFDemoProductService.GetEntityRequest();
            inValue.userInfo = userInfo;
            inValue.id = id;
            RDIFramework.Test.WCFDemoProductService.GetEntityResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).GetEntity(inValue);
            return retVal.GetEntityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.GetDTByIdsResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.GetDTByIds(RDIFramework.Test.WCFDemoProductService.GetDTByIdsRequest request) {
            return base.Channel.GetDTByIds(request);
        }
        
        public System.Data.DataTable GetDTByIds(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string[] ids) {
            RDIFramework.Test.WCFDemoProductService.GetDTByIdsRequest inValue = new RDIFramework.Test.WCFDemoProductService.GetDTByIdsRequest();
            inValue.userInfo = userInfo;
            inValue.ids = ids;
            RDIFramework.Test.WCFDemoProductService.GetDTByIdsResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).GetDTByIds(inValue);
            return retVal.GetDTByIdsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.GetDTByValuesResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.GetDTByValues(RDIFramework.Test.WCFDemoProductService.GetDTByValuesRequest request) {
            return base.Channel.GetDTByValues(request);
        }
        
        public System.Data.DataTable GetDTByValues(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.KeyValuePairOfstringanyType[] parameters) {
            RDIFramework.Test.WCFDemoProductService.GetDTByValuesRequest inValue = new RDIFramework.Test.WCFDemoProductService.GetDTByValuesRequest();
            inValue.userInfo = userInfo;
            inValue.parameters = parameters;
            RDIFramework.Test.WCFDemoProductService.GetDTByValuesResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).GetDTByValues(inValue);
            return retVal.GetDTByValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.BatchSaveResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.BatchSave(RDIFramework.Test.WCFDemoProductService.BatchSaveRequest request) {
            return base.Channel.BatchSave(request);
        }
        
        public int BatchSave(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, RDIFramework.Test.WCFDemoProductService.DemoProductEntity[] entites) {
            RDIFramework.Test.WCFDemoProductService.BatchSaveRequest inValue = new RDIFramework.Test.WCFDemoProductService.BatchSaveRequest();
            inValue.userInfo = userInfo;
            inValue.entites = entites;
            RDIFramework.Test.WCFDemoProductService.BatchSaveResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).BatchSave(inValue);
            return retVal.BatchSaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.DeleteResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.Delete(RDIFramework.Test.WCFDemoProductService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public int Delete(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string id) {
            RDIFramework.Test.WCFDemoProductService.DeleteRequest inValue = new RDIFramework.Test.WCFDemoProductService.DeleteRequest();
            inValue.userInfo = userInfo;
            inValue.id = id;
            RDIFramework.Test.WCFDemoProductService.DeleteResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).Delete(inValue);
            return retVal.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.BatchDeleteResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.BatchDelete(RDIFramework.Test.WCFDemoProductService.BatchDeleteRequest request) {
            return base.Channel.BatchDelete(request);
        }
        
        public int BatchDelete(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string[] ids) {
            RDIFramework.Test.WCFDemoProductService.BatchDeleteRequest inValue = new RDIFramework.Test.WCFDemoProductService.BatchDeleteRequest();
            inValue.userInfo = userInfo;
            inValue.ids = ids;
            RDIFramework.Test.WCFDemoProductService.BatchDeleteResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).BatchDelete(inValue);
            return retVal.BatchDeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDIFramework.Test.WCFDemoProductService.SetDeletedResponse RDIFramework.Test.WCFDemoProductService.IDemoProductService.SetDeleted(RDIFramework.Test.WCFDemoProductService.SetDeletedRequest request) {
            return base.Channel.SetDeleted(request);
        }
        
        public int SetDeleted(RDIFramework.Test.WCFDemoProductService.UserInfo userInfo, string[] ids) {
            RDIFramework.Test.WCFDemoProductService.SetDeletedRequest inValue = new RDIFramework.Test.WCFDemoProductService.SetDeletedRequest();
            inValue.userInfo = userInfo;
            inValue.ids = ids;
            RDIFramework.Test.WCFDemoProductService.SetDeletedResponse retVal = ((RDIFramework.Test.WCFDemoProductService.IDemoProductService)(this)).SetDeleted(inValue);
            return retVal.SetDeletedResult;
        }
    }
}
